# Generated by Django 2.0.2 on 2019-05-20 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0002_auto_20190519_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('materialId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.Contents')),
            ],
        ),
    ]
