# Generated by Django 2.0.2 on 2019-05-19 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contents',
            old_name='lesson_id',
            new_name='lessonId',
        ),
    ]
