# Generated by Django 2.0.2 on 2019-05-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionText', models.TextField()),
                ('answer', models.BooleanField(default=False)),
            ],
        ),
    ]
