# Generated by Django 2.0.2 on 2019-05-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('courses', '0002_auto_20190428_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lessons')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
            ],
        ),
    ]
